### ISSUE TITLE
TPK generation fails because its not using https

### ISSUE THREAD

**Issue by barkerpc** [nixta/tpk-creator#2]
@nixta just tried this out and the urls need to be updated to force https otherwise the job is undefined

**Comment by nixta** [comment]
@barkerpc Could you expand on this please? I've just run it in both Chrome and Safari and the whole process seems to work just fine.

**Comment by nixta** [comment]
Ah. Are you seeing problems when you run the app in an `https` context, like https://nixta.github.io/tpk-creator/ ?

**Comment by nixta** [comment]
Once I switched to `https` I could reproduce (I think, either way it needed fixing).

Should be working now. See commit https://github.com/nixta/tpk-creator/commit/aa28cb3a183845912f7bb19a0d97a4fc11325b71 (I naughtily bypassed PRs!).

Thanks for pointing this out! Let me know if this doesn't resolve the issue you were seeing, @barkerpc.

**Comment by jgravois** [comment]
to each his own, but folks like Paul Irish consider relative links an [anti-pattern](https://twitter.com/paul_irish/status/588502455530311680?lang=en)...

**Comment by nixta** [comment]
Fair enough. It seems to depend on how well the TLS stack is implemented, but I guess we'll have to trust ArcGIS Online, and also realize that frankly it doesn't matter for this app.

See https://github.com/nixta/tpk-creator/pull/3

**Comment by barkerpc** [comment]
Nick looks good to me.  I'll buy you a beer next dev summit

**Comment by nixta** [comment]
It was a mighty difficult pair of find-replace operations, fully worthy of a beer ;)

**Comment by barkerpc** [comment]
haha true, but I'll still buy you one
