### ISSUE TITLE
No longer able to download tpks

### ISSUE THREAD

**Issue by ghost** [nixta/tpk-creator#4]
Did Esri change the API or policies regarding offline tpk generation?  The download button stays as a busy symbol.

Esri now offers a Tile Package Kreator that has account requirements to be useful.

**Comment by nixta** [comment]
Hmmm. Not sure. And also annoyed that I wasn't notified of this. Sorry!

**Comment by nixta** [comment]
Should be fixed now. Looks like there was something changed about the JQuery I was calling that no longer required JSON to be unpacked.
